import { Product } from './types/Product'

export const sampleProducts: Product[] = [
  {
    name: 'Nike Slim Shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '../images/p1.jpg',
    price: 1200,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Adidas Fit Shirt',
    slug: 'adidas-fit-shirt',
    category: 'Shirts',
    image: '../images/p2.jpg',
    price: 1800,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'high quality product',
  },
  {
    name: 'Lacoste Free Pants',
    slug: 'lacoste-free-pants',
    category: 'Pants',
    image: '../images/p3.jpg',
    price: 2500,
    countInStock: 0,
    brand: 'Lacoste',
    rating: 4.8,
    numReviews: 17,
    description: 'high quality product',
  },
  {
    name: 'Nike Slim Pants',
    slug: 'nike-slim-pants',
    category: 'Pants',
    image: '../images/p4.jpg',
    price: 2000,
    countInStock: 15,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 14,
    description: 'high quality product',
  },
  {
    name: 'Puma Running Shoe',
    slug: 'puma-running-shoe',
    category: 'Shoes',
    image: '../images/p5.jpg',
    price: 3000,
    countInStock: 8,
    brand: 'Puma',
    rating: 4.7,
    numReviews: 13,
    description: 'high quality running shoe',
  },
  {
    name: 'Adidas Running Shoe',
    slug: 'adidas-running-shoe',
    category: 'Shoes',
    image: '../images/p6.jpg',
    price: 3500,
    countInStock: 5,
    brand: 'Adidas',
    rating: 4.6,
    numReviews: 11,
    description: 'comfortable and durable running shoe',
  },
  {
    name: 'Nike Running Shoe',
    slug: 'nike-running-shoe',
    category: 'Shoes',
    image: '../images/p7.jpg',
    price: 3200,
    countInStock: 7,
    brand: 'Nike',
    rating: 4.8,
    numReviews: 16,
    description: 'lightweight and high performance running shoe',
  },
  {
    name: 'Asics Running Shoe',
    slug: 'asics-running-shoe',
    category: 'Shoes',
    image: '../images/p8.jpg',
    price: 2900,
    countInStock: 12,
    brand: 'Asics',
    rating: 4.7,
    numReviews: 9,
    description: 'ergonomically designed for comfort and speed',
  },
]